version: '3.8'
services:
  sh: &base
    build:
      context: .
      target: test
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: bash

  test:
    <<: *base
    command: bash -c "pip install -e . && pytest"

  picked:
    <<: *base
    command: bash -c "pip install -e . && pytest --picked"
