version: '3.8'
services:
  sh: &base
    build:
      context: .
      target: test
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: bash

  test:
    <<: *base
    command: bash -c "pip install -e . && pytest"

  picked:
    <<: *base
    command: bash -c "pip install -e . && pytest --picked"

  lint:
    <<: *base
    command: bash -c "find . -type f -name \"*.py\" | xargs pylint"

  task_a:
    build:
      context: .
      target: prod
    command: task_a --value-a 4 --value-b 5

  task_b:
    build:
      context: .
      target: prod
    command: task_b --value-a 4 --value-b 5
